def get_hotspots_schema():
  return [
     'result',
   	 'Function',
   	 'threads',
   	 'num_epochs',
   	 'num_trials',
   	 'train_file_name',
   	 'num_rows',
   	 'num_features',
   	 'density',
   	 'total_num_epochs',
   	 'model_size_kB',
   	 'num_nonzeroes',

		 'Clockticks',
   	 'Instructions Retired',
   	 'CPI Rate',
   	 'Front-End Bound(%)',
   	 'Bad Speculation(%)',
   	 'Bad Speculation:Branch Mispredict(%)',
   	 'Bad Speculation:Machine Clears(%)',
   	 'Back-End Bound:Memory Bound(%)',
   	 'Back-End Bound:Core Bound(%)',
   	 'Back-End Bound:Core Bound:Divider(%)',
   	 'Back-End Bound:Core Bound:Port Utilization(%)',

   	 'Front-End Bound(%)',
		 'Front-End Bound:Front-End Latency(%)',
   	 'Front-End Bound:Front-End Latency:ICache Misses(%)',
   	 'Front-End Bound:Front-End Latency:ITLB Overhead(%)',
   	 'Front-End Bound:Front-End Latency:Branch Resteers(%)',
   	 'Front-End Bound:Front-End Latency:DSB Switches(%)',
   	 'Front-End Bound:Front-End Latency:Length Changing Prefixes(%)',
   	 'Front-End Bound:Front-End Latency:MS Switches(%)',
   	 'Front-End Bound:Front-End Bandwidth(%)',
   	 'Front-End Bound:Front-End Bandwidth:Front-End Bandwidth MITE(%)',
   	 'Front-End Bound:Front-End Bandwidth:Front-End Bandwidth DSB(%)',
   	 'Front-End Bound:Front-End Bandwidth:Front-End Bandwidth LSD(%)',

   	 'Bad Speculation(%)',
   	 'Bad Speculation:Branch Mispredict(%)',
   	 'Bad Speculation:Machine Clears(%)',

   	 'Back-End Bound(%)',
   	 'Back-End Bound:Memory Bound(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:DTLB Overhead(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:Loads Blocked by Store Forwarding(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:Lock Latency(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:Split Loads(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:4K Aliasing(%)',
   	 'Back-End Bound:Memory Bound:L1 Bound:FB Full(%)',
   	 'Back-End Bound:Memory Bound:L3 Bound:Contested Accesses(%)',
   	 'Back-End Bound:Memory Bound:L3 Bound:Data Sharing(%)',
   	 'Back-End Bound:Memory Bound:L3 Bound:L3 Latency(%)',
   	 'Back-End Bound:Memory Bound:L3 Bound:SQ Full(%)',
   	 'Back-End Bound:Memory Bound:DRAM Bound:Memory Latency:Local DRAM(%)',
   	 'Back-End Bound:Memory Bound:DRAM Bound:Memory Latency:Remote DRAM(%)',
   	 'Back-End Bound:Memory Bound:DRAM Bound:Memory Latency:Remote Cache(%)',
   	 'Back-End Bound:Memory Bound:Store Bound(%)',
   	 'Back-End Bound:Memory Bound:Store Bound:Store Latency(%)',
   	 'Back-End Bound:Memory Bound:Store Bound:False Sharing(%)',
   	 'Back-End Bound:Memory Bound:Store Bound:Split Stores(%)',
   	 'Back-End Bound:Memory Bound:Store Bound:DTLB Store Overhead(%)',
   	 'Back-End Bound:Core Bound(%)',
   	 'Back-End Bound:Core Bound:Divider(%)',
   	 'Back-End Bound:Core Bound:Port Utilization(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 0 Ports Utilized(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 1 Port Utilized(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 2 Ports Utilized(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 0(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 1(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 2(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 3(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 4(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 5(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 6(%)',
   	 'Back-End Bound:Core Bound:Port Utilization:Cycles of 3+ Ports Utilized:Port 7(%)',
   	 'Retiring(%)',
   	 'Retiring:General Retirement(%)',
   	 'Retiring:Microcode Sequencer(%)',
   	 'Retiring:Microcode Sequencer:Assists(%)',
   	 'Module',
   	 'InstructionsPerEpoch',
   	 'TotalClockticksPerEpoch',
   ]
